model_name: VBD

# Data Config
# train_data_path: /home/huang/Mount_Disk/shy/vbd_dataset/train/processed
# val_data_path: /home/huang/Mount_Disk/shy/vbd_dataset/val/processed
# anchor_path: /home/huang/Mount_Disk/shy/VBD/vbd/data/cluster_64_center_dict.pkl
# log_dir: ./train_log
train_data_path: /home/karim/VBD/data/train
val_data_path: /home/karim/VBD/data/val
anchor_path: vbd/data/kmeans_navsim_traj_20.npy
log_dir: ./train_log

# Wandb Config
use_wandb: False
username: karim-sun
project: vbd
wandb_dir: ./wandb_logs # 自定义wandb日志的根目录

# Checkpoint Config
init_from: null

# Model Config
agents_len: 16
future_len: 40
action_len: 1
encoder_layers: 6

# Encoder
history_dropout: 0.2

# Task Probabilities for get_random_mask
task_probabilities:
  prediction: 0.8
  goal_conditioned: 0.08
  agent_reactive: 0.08
  reconstruction: 0.04

# Predictor
prediction_type: sample
encoder_version: v3 # v1: GRU, v2: MLP, v3: Self-Attention
use_gumbel_anneal: True
gumbel_tau_start: 1.0
gumbel_tau_end: 0.1
gumbel_anneal_steps: 4000

# Diffusion Params
diffusion_steps: 1000
#schedule_type: cosine  $$$
schedule_type: log
schedule_s: 0
schedule_e: 1
schedule_tau: 1

action_mean: [0.0, 0.0]
# action_std: [1.0, 0.15]
action_std: [1.0, 1.0]
clamp_value: 5.0

normalize_anchors: True
anchor_incre_min: [-0.2, -2]
anchor_incre_max: [7, 2]

# Training Params
seed: 21
batch_size: 2
num_workers: 20
accumulate_grad_batches: 1 # 会影响实际的lr steps等
lr: 0.0002 # 0.0002
weight_decay: 0.01
epochs: 12
lr_warmup_step: 600
lr_total_steps: 4800 # 估算的总训练步数 (例如: epochs * steps/epoch)
lr_end_factor: 0.025 # 学习率最终衰减到的比例 (initial_lr * lr_end_factor)
precision: "bf16-mixed"
random_target: 0.1

# Loss Weights
score_loss_type: "mix" # 'bce', 'rank', or 'mix'
use_dynamic_rank_weight: True
rank_weight_start: 0.0
rank_weight_end: 0.1
rank_weight_anneal_steps: 4800

use_focused_rank_loss: True
focused_rank_topk: 5
use_hinge_loss: False
soft_hinge_loss_weight: 0.1

bce_loss_weight: 1.0
goal_loss_weight: 0.8
score_loss_weight: 0.2
predictor_loss_weight: 1.0

traj_loss_weight: 0.4
denoise_loss_weight: 1.0
denoiser_loss_weight: 0.8

train_encoder: True
train_denoiser: True
train_predictor: True
