model_name: VBD

# Data Config
train_data_path: /media/huang/PortableSSD/train_processed/processed
# train_data_path: /media/huang/0CB911D80CB911D8/train_processed/processed
# train_data_path: /home/huang/Mount_Disk/shy/vbd_dataset/train/processed
val_data_path: /home/huang/Mount_Disk/shy/vbd_dataset/val/processed
anchor_path: vbd/data/16384.npy
cluster_path: vbd/data/clusters_nms.pkl
log_dir: ./train_log

# Wandb Config
use_wandb: True
username: karim-sun
project: vbd
wandb_dir: ./wandb_logs # 自定义wandb日志的根目录

# Checkpoint Config
init_from: null

# Model Config
agents_len: 16
future_len: 40
action_len: 1
encoder_layers: 6

# Encoder
history_dropout: 0.4

# Task Probabilities for get_random_mask
intent_dropout: 0.4
task_probabilities:
  prediction: 1.0
  goal_conditioned: 0.08
  agent_reactive: 0.08
  reconstruction: 0.04

# Predictor
prediction_type: sample
encoder_version: v3 # v1: GRU, v2: MLP, v3: Self-Attention

# Weight Annealing
balanced_input: prob # 'no', 'prob', 'linear'
weight_start: 0.8
weight_end: 0.0
weight_anneal_steps: 70000

# Diffusion Params
diffusion_steps: 1000
#schedule_type: cosine  $$$
schedule_type: log
schedule_s: 0
schedule_e: 1
schedule_tau: 1

action_mean: [0.0, 0.0]
# action_std: [1.0, 0.15]
action_std: [1.0, 1.0]
clamp_value: 5.0

normalize_anchors: True
anchor_incre_min: [-0.5, -2]
anchor_incre_max: [3.5, 2]

# Training Params
seed: 21
batch_size: 10
num_workers: 32
accumulate_grad_batches: 4 # 会影响实际的lr steps等
lr: 0.0002 # 0.0002
weight_decay: 0.01
epochs: 10
lr_warmup_step: 7000
lr_total_steps: 97420 # 估算的总训练步数 (例如: epochs * steps/epoch)
lr_end_factor: 0.025 # 学习率最终衰减到的比例 (initial_lr * lr_end_factor)
precision: "bf16-mixed"
random_target: 0.1

# Loss Weights
score_loss_type: "bce" # 'bce', 'rank', or 'mix'
use_dynamic_rank_weight: True
rank_weight_start: 0.0
rank_weight_end: 0.1
rank_weight_anneal_steps: 20000

use_focused_rank_loss: True
focused_rank_topk: 5
use_hinge_loss: False
soft_hinge_loss_weight: 0.1

bce_loss_weight: 0.8
goal_loss_weight: 2.0
score_loss_weight: 0.8
predictor_loss_weight: 1.0

traj_loss_weight: 100.0
denoise_loss_weight: 1.0
denoiser_loss_weight: 0.8

train_encoder: True
train_denoiser: True
train_predictor: True
